CREATE OR REPLACE PACKAGE GESTIONAR_CENTRO
IS
  --Declaración del paquete
TYPE CURSOR_CENTROS is ref cursor;

  PROCEDURE VISUALIZAR_LISTA_CENTRO(C_CENTROS OUT CURSOR_CENTROS);
  PROCEDURE VISUALIZAR_DATOS_CENTRO(P_ID IN NUMBER, C_CENTROS OUT CURSOR_CENTROS,PNUM_TRABAJADORES OUT NUMBER);
  PROCEDURE VISUALIZAR_DATOS_CENTRO_NOMBRE(P_NOMBRE IN VARCHAR2, C_CENTROS OUT CURSOR_CENTROS,PNUM_TRABAJADORES OUT NUMBER);
  
END;